CREATE TABLE auction_player_registrations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tournament_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    employee_id VARCHAR(100) NOT NULL,
    skype_id VARCHAR(100),
    mobile_no VARCHAR(20),
    playing_position VARCHAR(50) NOT NULL,
    batting_style VARCHAR(50),
    bowling_style VARCHAR(50),
    previous_experience TEXT,
    availability_status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
    profile_photo VARCHAR(500),
    emergency_contact VARCHAR(100),
    preferred_base_price INT,
    approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approved_by BIGINT,
    approved_at DATETIME,
    rejection_reason VARCHAR(500),
    created_player_id BIGINT,
    created_by BIGINT,
    created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by BIGINT,
    updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tournament_id) REFERENCES tournament(id),
    FOREIGN KEY (approved_by) REFERENCES players(id),
    FOREIGN KEY (created_player_id) REFERENCES players(id)
);
