CREATE TABLE auction_players (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tournament_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    player_type VARCHAR(20) NOT NULL,
    category VARCHAR(30),
    base_price INT NOT NULL DEFAULT 500,
    current_bid INT,
    current_highest_team_id BIGINT,
    sold_to_team_id BIGINT,
    final_price INT,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    auction_round INT NOT NULL DEFAULT 1,
    player_rating DECIMAL(4,2),
    sequence_order INT,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_by BIGINT,
    updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tournament_id) REFERENCES tournament(id),
    FOREIGN KEY (player_id) REFERENCES players(id),
    FOREIGN KEY (current_highest_team_id) REFERENCES team(id),
    FOREIGN KEY (sold_to_team_id) REFERENCES team(id),
    UNIQUE KEY uk_auction_tournament_player (tournament_id, player_id)
);
